apiVersion: v1
kind: Service
metadata:
  name: socket-io-benchmark
  labels:
    app: socket-io-benchmark
    service: socket-io-benchmark
spec:
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
      name: http
  type: ClusterIP
  selector:
    app: socket-io-benchmark
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: socket-io-benchmark
  labels:
    app: socket-io-benchmark
    version: v1
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: socket-io-benchmark
      version: v1
  template:
    metadata:
      labels:
        app: socket-io-benchmark
        version: v1
    spec:
      containers:
        - env:
            - name: PORT
              value: "3000"
          image: jozhe/socket-io-benchmark:latest
          imagePullPolicy: Never
          name: socket-io-benchmark
          ports:
            - containerPort: 3000
